### PR TITLE
MergeAway game added

### PR DESCRIPTION
**Pull request by karlson35**

### CODE REVIEW

**Comment by sako444** [comment]
Need twerk race promo id and app token

**Comment by virginpixel** [comment]
"6": {
            "name": "Twerk Race 3D",
            "appToken": "61308365-9d16-4040-8bb0-2f4a4c69074c",
            "promoId": "61308365-9d16-4040-8bb0-2f4a4c69074c"
        }

**Comment by sweethome29** [comment]
> "6": { "name": "Twerk Race 3D", "appToken": "61308365-9d16-4040-8bb0-2f4a4c69074c", "promoId": "61308365-9d16-4040-8bb0-2f4a4c69074c" }

is there a mistake? apptoken and promoid are the same.
where does this information come from? how do i get tokens for future games myself?

**Comment by virginpixel** [comment]
No its not a mistake. I have added the line to config.json and tested. It works.

**Pull request closed without merging**
